name: AcademicCalendar CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: net-core

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      shell: pwsh
      run: docker build . --file Dockerfile --tag academic-calendar:$([DateTimeOffset]::Now.ToUnixTimeSeconds())
